---
dependencies: []

galaxy_info:
  author: Olivier Locard
  description: Nexus for Linux
  company: "Deveryware"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.9
  platforms:
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - all
  galaxy_tags:
    - nexus
    - development
    - storage
