---

#tasks file for mule installation 

- name: Download mule_package
  get_url: url=http://s3.amazonaws.com/70aaf9be67f9bf88e5e78adcd7d6aa34/mule-ee-distribution-standalone-${RUNTIME_VERSION}.tar.gz 
  sudo: true

- name: Unpack mule
  unarchive:
    src= "mule-ee-distribution-standalone-${RUNTIME_VERSION}.zip"
    dest= "/opt"
    force=no
    copy=false
    mode="0755"
  tags: unpack


  # Environment setup.
- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home != ''


- name: Start Mule
  template:
    src: startMule.sh
    dest: /opt/startMule.sh
    mode: 0644


